service: serverless

provider:
  name: aws
  runtime: nodejs12.3
  profile: OneShiv

plugins:
  - serverless-offline

functions:
  helloworld:
    handler: src/helloworld.handler
  newhello:
    handler: src/helloworld.newhello

    
